FROM registry.jharmison.com/rhel/bootc:latest

# Install audio firmware
RUN --mount=target=/var/cache,type=tmpfs --mount=target=/var/cache/dnf,type=cache,id=dnf-cache \
  dnf -y install \
  alsa-sof-firmware \
  iwl7260-firmware
