FROM registry.jharmison.com/rhel/bootc:latest

# Install audio firmware
RUN --mount=type=tmpfs,target=/var/cache --mount=type=cache,target=/var/cache/dnf,id=dnf-cache \
    dnf -y install \
    alsa-sof-firmware \
    iwl7260-firmware
