FROM registry.jharmison.com/rhel/bootc:fz40-base

RUN dnf install -y gnome-shell gnome-kiosk gnome-kiosk-script-session firefox unzip
# The GUI user needs logged into without a password
COPY overlays/gui/ /
COPY overlays/kiosk/ /
