FROM registry.jharmison.com/rhel/bootc:fz40-base

RUN --mount=type=tmpfs,target=/var/cache --mount=type=cache,target=/var/cache/dnf,id=dnf-cache \
    dnf install -y gnome-shell gnome-kiosk gnome-kiosk-script-session firefox

# The GUI user needs logged into without a password
COPY overlays/gui/ /
COPY overlays/kiosk/ /
