FROM registry.jharmison.com/rhel/bootc:fz40-kernel as kernel

FROM registry.redhat.io/rhel9/rhel-bootc:9.5 as policy-build

COPY overlays/fz40-policy-build/ /

WORKDIR /policy

# Perform some basic package installation
RUN --mount=type=tmpfs,target=/var/cache --mount=type=cache,target=/var/cache/dnf,id=dnf-cache \
    dnf -y install selinux-policy-devel

RUN make -f /usr/share/selinux/devel/Makefile panasonic_programmable_keys.pp


FROM registry.jharmison.com/rhel/bootc:fz40-base

# Install a GUI
RUN --mount=type=tmpfs,target=/var/cache --mount=type=cache,target=/var/cache/dnf,id=dnf-cache \
    dnf -y group install GNOME base-x Fonts \
    && dnf -y install firefox

# The GUI user needs logged into without a password
COPY overlays/gui/ /

# Configurations for loading the built SELinux policy and setting Panasonic branding
COPY overlays/fz40-gui/ /
COPY --from=policy-build /policy/panasonic_programmable_keys.pp /usr/share/panasonic/

# Install the key configuration application
RUN --mount=type=tmpfs,target=/var/cache --mount=type=cache,target=/var/cache/dnf,id=dnf-cache \
    dnf -y install qt5 qt5-qtwayland

# Attempt to install the SELinux policy module
RUN semodule -i /usr/share/panasonic/panasonic_programmable_keys.pp

# Install custom kernel
RUN --mount=type=tmpfs,target=/var/cache --mount=type=cache,target=/var/cache/dnf,id=dnf-cache \
    --mount=type=bind,from=kernel,src=/build/dist/RPMS/x86_64/,target=/build \
    rpm-ostree cliwrap install-to-root / \
    && rpm-ostree override replace $(find /build -name 'kernel-5*' -o -name 'kernel-core-5*' -o -name 'kernel-modules-5*' -o -name 'kernel-modules-core-5*') \
    && ostree container commit

# HACK: Install programmable keys application
RUN --mount=type=tmpfs,target=/var/roothome/.cache --mount=type=cache,target=/var/roothome/.cache/pip,id=pip-cache \
    python3.12 -m venv /usr/local/lib/panasonic-programmable-keys \
    && /usr/local/lib/panasonic-programmable-keys/bin/pip install --upgrade pip setuptools wheel \
    && /usr/local/lib/panasonic-programmable-keys/bin/pip install panasonic-programmable-keys==0.2.4 \
    && ln -s /usr/local/lib/panasonic-programmable-keys/bin/panasonic-programmable-keys /usr/local/bin/panasonic-programmable-keys \
    && /usr/local/bin/panasonic-programmable-keys install \
    && update-desktop-database
