FROM registry.jharmison.com/rhel/bootc:latest

# Install a GUI
RUN --mount=target=/var/cache,type=tmpfs --mount=target=/var/cache/dnf,type=cache,id=dnf-cache \
  dnf -y group install GNOME base-x Fonts

# The GUI user needs logged into obviously
COPY overlays/gui/ /
